import type { TrackingEventLog } from "./tracking-event-log";

/** Demo feed for the Tracking events drawer (replace with API data later). */
export const MOCK_TRACKING_EVENT_LOGS: TrackingEventLog[] = [
  {
    id: "ev-01",
    flowName: "Flow 1",
    flowRoute: "Career site 1 → Bullhorn",
    time: "10:42:18",
    recordedAt: "2026-03-08T10:42:18.000Z",
    event: "VIEW",
    jobId: "TH-9214",
    jtrack: "abc-1f2k",
    identityResolution: "cookie",
    method: "Image Pixel",
    pageUrl: "https://career.tenethealth.com/jobs/nursing",
    status: "received",
  },
  {
    id: "ev-02",
    flowName: "Flow 1",
    flowRoute: "Career site 1 → Bullhorn",
    time: "10:41:02",
    recordedAt: "2026-03-08T10:41:02.000Z",
    event: "LEAD",
    jobId: "TH-9214",
    jtrack: "abc-1f2k",
    identityResolution: "fingerprint",
    method: "JS Pixel",
    pageUrl: "https://career.tenethealth.com/jobs/nursing?utm_source=google",
    status: "received",
  },
  {
    id: "ev-03",
    flowName: "Flow 2",
    flowRoute: "Career site 2 → Workday",
    time: "10:38:55",
    recordedAt: "2026-03-08T10:38:55.000Z",
    event: "APPLY_START",
    jobId: "TH-8801",
    jtrack: "def-9x2m",
    identityResolution: "cookie",
    method: "Image Pixel",
    pageUrl: "https://career.tenethealth.com/apply/start?job=8801",
    status: "warning",
  },
  {
    id: "ev-04",
    flowName: "Flow 1",
    flowRoute: "Career site 1 → Bullhorn",
    time: "10:35:12",
    recordedAt: "2026-03-08T10:35:12.000Z",
    event: "APPLY_FINISH",
    jobId: "TH-9214",
    jtrack: "abc-1f2k",
    identityResolution: "cookie",
    method: "JS Pixel",
    pageUrl: "https://career.tenethealth.com/apply/thank-you",
    status: "received",
  },
  {
    id: "ev-05",
    flowName: "Flow 3",
    flowRoute: "Career site 1 → Workday",
    time: "10:30:44",
    recordedAt: "2026-03-08T10:30:44.000Z",
    event: "VIEW",
    jobId: "TH-7012",
    jtrack: "ghi-3plq",
    identityResolution: "unattributed",
    method: "Image Pixel",
    pageUrl: "https://jobs.tenet.com/referral/7012",
    status: "failed",
  },
  {
    id: "ev-06",
    flowName: "Flow 2",
    flowRoute: "Career site 2 → Workday",
    time: "10:28:09",
    recordedAt: "2026-03-08T10:28:09.000Z",
    event: "Custom: Talent Community",
    jobId: "TH-8801",
    jtrack: "def-9x2m",
    identityResolution: "fingerprint",
    method: "S2S",
    endpointUrl: "https://api.tenet.io/v1/tracking/events",
    status: "received",
  },
  {
    id: "ev-07",
    flowName: "Flow 4",
    flowRoute: "Career site 2 → Bullhorn",
    time: "10:22:31",
    recordedAt: "2026-03-08T10:22:31.000Z",
    event: "LEAD",
    jobId: "TH-5540",
    jtrack: "jkl-88aa",
    identityResolution: "cookie",
    method: "JS Pixel",
    pageUrl: "https://career.tenethealth.com/events",
    status: "received",
  },
  {
    id: "ev-08",
    flowName: "Flow 1",
    flowRoute: "Career site 1 → Bullhorn",
    time: "10:18:00",
    recordedAt: "2026-03-08T10:18:00.000Z",
    event: "APPLY_START",
    jobId: "TH-9100",
    jtrack: "mno-zz99",
    identityResolution: "fingerprint",
    method: "Image Pixel",
    pageUrl: "https://career.tenethealth.com/apply/9100",
    status: "warning",
  },
  {
    id: "ev-09",
    flowName: "Flow 3",
    flowRoute: "Career site 1 → Workday",
    time: "10:12:47",
    recordedAt: "2026-03-08T10:12:47.000Z",
    event: "APPLY_FINISH",
    jobId: "TH-7012",
    jtrack: "missing",
    identityResolution: "fingerprint",
    method: "S2S",
    endpointUrl: "https://workday-proxy.tenet.io/s2s/apply-complete",
    status: "warning",
  },
  {
    id: "ev-10",
    flowName: "Flow 2",
    flowRoute: "Career site 2 → Workday",
    time: "10:05:22",
    recordedAt: "2026-03-08T10:05:22.000Z",
    event: "VIEW",
    jobId: "TH-8802",
    jtrack: "pqr-1122",
    identityResolution: "cookie",
    method: "Image Pixel",
    pageUrl: "https://career.tenethealth.com/jobs/radiology",
    status: "received",
  },
  {
    id: "ev-11",
    flowName: "Flow 4",
    flowRoute: "Career site 2 → Bullhorn",
    time: "09:58:11",
    recordedAt: "2026-03-08T09:58:11.000Z",
    event: "LEAD",
    jobId: "TH-5540",
    jtrack: "stu-4455",
    identityResolution: "unattributed",
    method: "JS Pixel",
    pageUrl: "https://career.tenethealth.com/jobs/pharmacy",
    status: "failed",
  },
  {
    id: "ev-12",
    flowName: "Flow 1",
    flowRoute: "Career site 1 → Bullhorn",
    time: "09:51:33",
    recordedAt: "2026-03-08T09:51:33.000Z",
    event: "VIEW",
    jobId: "TH-9215",
    jtrack: "vwx-7788",
    identityResolution: "fingerprint",
    method: "Image Pixel",
    pageUrl: "https://career.tenethealth.com/",
    status: "received",
  },
  {
    id: "ev-13",
    flowName: "Flow 3",
    flowRoute: "Career site 1 → Workday",
    time: "09:44:19",
    recordedAt: "2026-03-08T09:44:19.000Z",
    event: "APPLY_START",
    jobId: "TH-7013",
    jtrack: "yza-9900",
    identityResolution: "cookie",
    method: "JS Pixel",
    pageUrl: "https://career.tenethealth.com/apply/7013",
    status: "received",
  },
  {
    id: "ev-14",
    flowName: "Flow 2",
    flowRoute: "Career site 2 → Workday",
    time: "09:40:08",
    recordedAt: "2026-03-08T09:40:08.000Z",
    event: "APPLY_FINISH",
    jobId: "TH-8802",
    jtrack: "pqr-1122",
    identityResolution: "fingerprint",
    method: "Image Pixel",
    pageUrl: "https://career.tenethealth.com/apply/done",
    status: "warning",
  },
  {
    id: "ev-15",
    flowName: "Flow 4",
    flowRoute: "Career site 2 → Bullhorn",
    time: "09:33:50",
    recordedAt: "2026-03-08T09:33:50.000Z",
    event: "VIEW",
    jobId: "TH-5541",
    jtrack: "bcd-3344",
    identityResolution: "cookie",
    method: "S2S",
    endpointUrl: "https://api.tenet.io/v1/pageview",
    status: "received",
  },
  {
    id: "ev-16",
    flowName: "Flow 1",
    flowRoute: "Career site 1 → Bullhorn",
    time: "09:28:14",
    recordedAt: "2026-03-08T09:28:14.000Z",
    event: "LEAD",
    jobId: "TH-9215",
    jtrack: "vwx-7788",
    identityResolution: "unattributed",
    method: "JS Pixel",
    pageUrl: "https://career.tenethealth.com/jobs?ref=email",
    status: "received",
  },
  {
    id: "ev-17",
    flowName: "Flow 3",
    flowRoute: "Career site 1 → Workday",
    time: "09:15:02",
    recordedAt: "2026-03-08T09:15:02.000Z",
    event: "VIEW",
    jobId: "TH-7014",
    jtrack: "efg-5566",
    identityResolution: "fingerprint",
    method: "Image Pixel",
    pageUrl: "https://jobs.tenet.com/7014",
    status: "failed",
  },
  {
    id: "ev-18",
    flowName: "Flow 2",
    flowRoute: "Career site 2 → Workday",
    time: "09:02:41",
    recordedAt: "2026-03-08T09:02:41.000Z",
    event: "Custom: SMS Click",
    jobId: "TH-8803",
    jtrack: "hij-2211",
    identityResolution: "cookie",
    method: "S2S",
    endpointUrl: "https://engage.tenet.io/track/sms",
    status: "received",
  },
];
